wandb_version: 1

CastToTensor:
  desc: null
  value: true
Learner:
  desc: null
  value:
    _name: <fastai.learner.Learner object at 0x0000028DF0E19210>
    arch: maxvit_rmlp_small_rw_224.sw_in1k
    default_cbs: true
    loss_func:
      _name: FlattenedLoss of BCEWithLogitsLoss()
      axis: -1
      flatten: true
      floatify: true
      is_2d: false
    lr: 0.001
    metrics:
    - fastai.metrics.error_rate
    - fastai.metrics.accuracy_multi
    model_dir: models
    moms:
    - 0.95
    - 0.85
    - 0.95
    n_out: 17
    normalize: true
    opt_func: fastai.optimizer.Adam
    path: C:\Users\GCM\.fastai\data\planet_sample
    pretrained: true
    splitter: fastai.vision.learner.default_split
    train_bn: true
    wd: null
    wd_bn_bias: false
MixedPrecision:
  desc: null
  value: true
ParamScheduler:
  desc: null
  value: true
ProgressCallback:
  desc: null
  value: true
Recorder:
  desc: null
  value:
    add_time: true
    train_metrics: false
    valid_metrics: true
TrainEvalCallback:
  desc: null
  value: true
WandbCallback:
  desc: null
  value:
    dataset_name: null
    log: all
    log_dataset: false
    log_model: false
    log_preds: true
    log_preds_every_epoch: false
    model_name: null
    n_preds: 36
    reorder: true
    seed: 12345
    valid_dl: null
_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: fastai
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.9
    session_history: code\_session_history.ipynb
    start_time: 1678739378.592025
    t:
      1:
      - 1
      - 4
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 4
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 2
      - 16
      - 23
      4: 3.10.9
      5: 0.13.10
      8:
      - 1
      - 3
      - 5
batch per epoch:
  desc: null
  value: 400
batch size:
  desc: null
  value: 2
batch_size:
  desc: null
  value: 2
dataset.tfms:
  desc: null
  value: '[Pipeline: ColReader -- {''cols'': 0, ''pref'': ''C:\\Users\\GCM\\.fastai\\data\\planet_sample\\train\\'',
    ''suff'': ''.jpg'', ''label_delim'': None} -> PILBase.create, Pipeline: ColReader
    -- {''cols'': 1, ''pref'': '''', ''suff'': '''', ''label_delim'': '' ''} -> MultiCategorize
    -- {''vocab'': None, ''sort'': True, ''add_na'': False} -> OneHotEncode -- {''c'':
    None}]'
device:
  desc: null
  value: cuda
dls.after_batch:
  desc: null
  value: "Pipeline: IntToFloatTensor -- {'div': 255.0, 'div_mask': 1} -> Normalize\
    \ -- {'mean': tensor([[[[0.5000]],\n\n         [[0.5000]],\n\n         [[0.5000]]]],\
    \ device='cuda:0'), 'std': tensor([[[[0.5000]],\n\n         [[0.5000]],\n\n  \
    \       [[0.5000]]]], device='cuda:0'), 'axes': (0, 2, 3)}"
dls.after_item:
  desc: null
  value: 'Pipeline: Resize -- {''size'': (224, 224), ''method'': ''crop'', ''pad_mode'':
    ''reflection'', ''resamples'': (<Resampling.BILINEAR: 2>, <Resampling.NEAREST:
    0>), ''p'': 1.0} -> ToTensor'
dls.before_batch:
  desc: null
  value: 'Pipeline: '
epochs:
  desc: null
  value: 3
frozen:
  desc: null
  value: true
frozen idx:
  desc: null
  value: 1
img_size:
  desc: null
  value: 224
input 1 dim 1:
  desc: null
  value: 2
input 1 dim 2:
  desc: null
  value: 3
input 1 dim 3:
  desc: null
  value: 224
input 1 dim 4:
  desc: null
  value: 224
model parameters:
  desc: null
  value: 64925276
model_name:
  desc: null
  value: maxvit_rmlp_small_rw_224.sw_in1k
n_inp:
  desc: null
  value: 1
pretrained:
  desc: null
  value: true
seed:
  desc: null
  value: 42
