wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1676235109.107021
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.9
      5: 0.13.10
      8:
      - 1
      - 3
      - 5
    visualize:
      val_conf_mat:
        panel_config:
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          panelDefId: wandb/confusion_matrix/v1
          stringSettings:
            title: ''
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: val_conf_mat_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
acc_task:
  desc: null
  value: multiclass
lr:
  desc: null
  value: 0.0031680784295770154
n_classes:
  desc: null
  value: 10
