wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1676067373.135223
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.9
      5: 0.13.10
      8:
      - 1
      - 3
      - 5
acc_task:
  desc: null
  value: multiclass
lr:
  desc: null
  value: 0.0034965187866565577
n_classes:
  desc: null
  value: 10
n_layer_1:
  desc: null
  value: 512
n_layer_2:
  desc: null
  value: 512
