wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1676002206.132933
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.9
      5: 0.13.10
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.5
epochs:
  desc: null
  value: 1
fc_layer_size:
  desc: null
  value: 256
learning_rate:
  desc: null
  value: 0.06703384346649212
optimizer:
  desc: null
  value: sgd
