wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: fastai
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.9
    session_history: code\_session_history.ipynb
    start_time: 1678732420.197024
    t:
      1:
      - 1
      - 4
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 4
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 2
      - 16
      - 23
      4: 3.10.9
      5: 0.13.10
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 8
epochs:
  desc: null
  value: 3
img_size:
  desc: null
  value: 224
model_name:
  desc: null
  value: maxvit_rmlp_small_rw_224.sw_in1k
pretrained:
  desc: null
  value: true
seed:
  desc: null
  value: 42
