wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: val_conf_mat_table._type
      5: 1
      6:
      - 1
    - 1: val_conf_mat_table.sha256
      5: 1
      6:
      - 1
    - 1: val_conf_mat_table.size
      5: 1
      6:
      - 1
    - 1: val_conf_mat_table.artifact_path
      5: 1
      6:
      - 1
    - 1: val_conf_mat_table._latest_artifact_path
      5: 1
      6:
      - 1
    - 1: val_conf_mat_table.path
      5: 1
      6:
      - 1
    - 1: val_conf_mat_table.ncols
      5: 1
      6:
      - 1
    - 1: val_conf_mat_table.nrows
      5: 1
      6:
      - 1
    - 1: val_loss
      5: 1
      6:
      - 1
    - 1: val_acc
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: test_conf_mat_table._type
      5: 1
      6:
      - 1
    - 1: test_conf_mat_table.sha256
      5: 1
      6:
      - 1
    - 1: test_conf_mat_table.size
      5: 1
      6:
      - 1
    - 1: test_conf_mat_table.artifact_path
      5: 1
      6:
      - 1
    - 1: test_conf_mat_table._latest_artifact_path
      5: 1
      6:
      - 1
    - 1: test_conf_mat_table.path
      5: 1
      6:
      - 1
    - 1: test_conf_mat_table.ncols
      5: 1
      6:
      - 1
    - 1: test_conf_mat_table.nrows
      5: 1
      6:
      - 1
    - 1: test_loss
      5: 1
      6:
      - 1
    - 1: test_acc
      5: 1
      6:
      - 1
    python_version: 3.10.9
    start_time: 1676234633.183086
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      3:
      - 2
      - 7
      - 23
      4: 3.10.9
      5: 0.13.10
      8:
      - 1
      - 3
      - 5
    visualize:
      test_conf_mat:
        panel_config:
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          panelDefId: wandb/confusion_matrix/v1
          stringSettings:
            title: ''
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: test_conf_mat_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      val_conf_mat:
        panel_config:
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          panelDefId: wandb/confusion_matrix/v1
          stringSettings:
            title: ''
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: val_conf_mat_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
acc_task:
  desc: null
  value: multiclass
lr:
  desc: null
  value: 0.001
n_classes:
  desc: null
  value: 10
