wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: huggingface
    huggingface_version: 4.26.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: sample_images._type
      5: 1
      6:
      - 1
    - 1: sample_images.width
      5: 1
      6:
      - 1
    - 1: sample_images.height
      5: 1
      6:
      - 1
    - 1: sample_images.format
      5: 1
      6:
      - 1
    - 1: sample_images.count
      5: 1
      6:
      - 1
    - 1: sample_images.filenames
      5: 1
      6:
      - 1
    - 1: sample_images.captions
      5: 1
      6:
      - 1
    - 1: sample_table._type
      5: 1
      6:
      - 1
    - 1: sample_table.sha256
      5: 1
      6:
      - 1
    - 1: sample_table.size
      5: 1
      6:
      - 1
    - 1: sample_table.artifact_path
      5: 1
      6:
      - 1
    - 1: sample_table._latest_artifact_path
      5: 1
      6:
      - 1
    - 1: sample_table.path
      5: 1
      6:
      - 1
    - 1: sample_table.ncols
      5: 1
      6:
      - 1
    - 1: sample_table.nrows
      5: 1
      6:
      - 1
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: train_accuracy
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val_loss
      5: 1
      6:
      - 1
    - 1: val_accuracy
      5: 1
      6:
      - 1
    python_version: 3.10.9
    start_time: 1677609492.019611
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      3:
      - 2
      - 7
      - 23
      4: 3.10.9
      5: 0.13.10
      6: 4.26.1
      8:
      - 1
      - 3
      - 5
lr:
  desc: null
  value: 0.001
n_classes:
  desc: null
  value: 10
n_layer_1:
  desc: null
  value: 128
n_layer_2:
  desc: null
  value: 128
