wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: huggingface
    huggingface_version: 4.26.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: train/acc
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val/loss
      5: 1
      6:
      - 1
    - 1: val/acc
      5: 1
      6:
      - 1
    - 1: test/loss
      5: 1
      6:
      - 1
    - 1: test/acc
      5: 1
      6:
      - 1
    python_version: 3.10.9
    session_history: code\_session_history.ipynb
    start_time: 1678304075.297375
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      3:
      - 2
      - 7
      - 23
      4: 3.10.9
      5: 0.13.10
      6: 4.26.1
      8:
      - 1
      - 3
      - 5
acc_task:
  desc: null
  value: multiclass
input_shape:
  desc: null
  value:
  - 3
  - 300
  - 300
learning_rate:
  desc: null
  value: 0.0002
num_classes:
  desc: null
  value: 196
transfer:
  desc: null
  value: true
